// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: fee/v1/fee.proto

package feepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FeeService_GetFeeTier_FullMethodName    = "/fee.v1.FeeService/GetFeeTier"
	FeeService_CalculateFees_FullMethodName = "/fee.v1.FeeService/CalculateFees"
)

// FeeServiceClient is the client API for FeeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FeeServiceClient interface {
	GetFeeTier(ctx context.Context, in *GetFeeTierRequest, opts ...grpc.CallOption) (*GetFeeTierResponse, error)
	CalculateFees(ctx context.Context, in *CalculateFeesRequest, opts ...grpc.CallOption) (*CalculateFeesResponse, error)
}

type feeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFeeServiceClient(cc grpc.ClientConnInterface) FeeServiceClient {
	return &feeServiceClient{cc}
}

func (c *feeServiceClient) GetFeeTier(ctx context.Context, in *GetFeeTierRequest, opts ...grpc.CallOption) (*GetFeeTierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFeeTierResponse)
	err := c.cc.Invoke(ctx, FeeService_GetFeeTier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feeServiceClient) CalculateFees(ctx context.Context, in *CalculateFeesRequest, opts ...grpc.CallOption) (*CalculateFeesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateFeesResponse)
	err := c.cc.Invoke(ctx, FeeService_CalculateFees_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeeServiceServer is the server API for FeeService service.
// All implementations must embed UnimplementedFeeServiceServer
// for forward compatibility.
type FeeServiceServer interface {
	GetFeeTier(context.Context, *GetFeeTierRequest) (*GetFeeTierResponse, error)
	CalculateFees(context.Context, *CalculateFeesRequest) (*CalculateFeesResponse, error)
	mustEmbedUnimplementedFeeServiceServer()
}

// UnimplementedFeeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFeeServiceServer struct{}

func (UnimplementedFeeServiceServer) GetFeeTier(context.Context, *GetFeeTierRequest) (*GetFeeTierResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeeTier not implemented")
}
func (UnimplementedFeeServiceServer) CalculateFees(context.Context, *CalculateFeesRequest) (*CalculateFeesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateFees not implemented")
}
func (UnimplementedFeeServiceServer) mustEmbedUnimplementedFeeServiceServer() {}
func (UnimplementedFeeServiceServer) testEmbeddedByValue()                    {}

// UnsafeFeeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeeServiceServer will
// result in compilation errors.
type UnsafeFeeServiceServer interface {
	mustEmbedUnimplementedFeeServiceServer()
}

func RegisterFeeServiceServer(s grpc.ServiceRegistrar, srv FeeServiceServer) {
	// If the following call pancis, it indicates UnimplementedFeeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FeeService_ServiceDesc, srv)
}

func _FeeService_GetFeeTier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeeTierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeeServiceServer).GetFeeTier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeeService_GetFeeTier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeeServiceServer).GetFeeTier(ctx, req.(*GetFeeTierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeeService_CalculateFees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateFeesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeeServiceServer).CalculateFees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeeService_CalculateFees_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeeServiceServer).CalculateFees(ctx, req.(*CalculateFeesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FeeService_ServiceDesc is the grpc.ServiceDesc for FeeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FeeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fee.v1.FeeService",
	HandlerType: (*FeeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFeeTier",
			Handler:    _FeeService_GetFeeTier_Handler,
		},
		{
			MethodName: "CalculateFees",
			Handler:    _FeeService_CalculateFees_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fee/v1/fee.proto",
}
