// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: risk/v1/risk.proto

package riskpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Risk_PreTradeCheck_FullMethodName = "/risk.v1.Risk/PreTradeCheck"
)

// RiskClient is the client API for Risk service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RiskClient interface {
	PreTradeCheck(ctx context.Context, in *PreTradeCheckRequest, opts ...grpc.CallOption) (*PreTradeCheckResponse, error)
}

type riskClient struct {
	cc grpc.ClientConnInterface
}

func NewRiskClient(cc grpc.ClientConnInterface) RiskClient {
	return &riskClient{cc}
}

func (c *riskClient) PreTradeCheck(ctx context.Context, in *PreTradeCheckRequest, opts ...grpc.CallOption) (*PreTradeCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreTradeCheckResponse)
	err := c.cc.Invoke(ctx, Risk_PreTradeCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RiskServer is the server API for Risk service.
// All implementations must embed UnimplementedRiskServer
// for forward compatibility.
type RiskServer interface {
	PreTradeCheck(context.Context, *PreTradeCheckRequest) (*PreTradeCheckResponse, error)
	mustEmbedUnimplementedRiskServer()
}

// UnimplementedRiskServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRiskServer struct{}

func (UnimplementedRiskServer) PreTradeCheck(context.Context, *PreTradeCheckRequest) (*PreTradeCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreTradeCheck not implemented")
}
func (UnimplementedRiskServer) mustEmbedUnimplementedRiskServer() {}
func (UnimplementedRiskServer) testEmbeddedByValue()              {}

// UnsafeRiskServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RiskServer will
// result in compilation errors.
type UnsafeRiskServer interface {
	mustEmbedUnimplementedRiskServer()
}

func RegisterRiskServer(s grpc.ServiceRegistrar, srv RiskServer) {
	// If the following call pancis, it indicates UnimplementedRiskServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Risk_ServiceDesc, srv)
}

func _Risk_PreTradeCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreTradeCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServer).PreTradeCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Risk_PreTradeCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServer).PreTradeCheck(ctx, req.(*PreTradeCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Risk_ServiceDesc is the grpc.ServiceDesc for Risk service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Risk_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "risk.v1.Risk",
	HandlerType: (*RiskServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PreTradeCheck",
			Handler:    _Risk_PreTradeCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "risk/v1/risk.proto",
}
